apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-wcs-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-wcs-app
  uid: dc948376-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '9380961'
  generation: 770
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-wcs-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-wcs-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-wcs-app@sha256:b0b2cfef4f63aff9dc69f9d357d161cafcdcb123cf74c84566e528270e958f9e
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-wcs-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-wcs-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-wcs
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-wcs-app
          image: >-
            172.30.181.173:5000/o2/omar-wcs-app@sha256:b0b2cfef4f63aff9dc69f9d357d161cafcdcb123cf74c84566e528270e958f9e
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
            - name: BUCKETS
              value: o2-test-data
            - name: OSSIM_PREFS_FILE
              value: /usr/share/ossim/ossim-site-preferences
            - name: OSSIM_DATA
              value: /data
            - name: OSSIM_INSTALL_PREFIX
              value: /usr
          resources: {}
          volumeMounts:
            - name: volume-wcs
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
            runAsUser: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 761
  observedGeneration: 770
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-wcs-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T18:15:52Z'
      lastTransitionTime: '2017-10-31T18:15:52Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-12-06T18:14:19Z'
      lastTransitionTime: '2017-12-06T18:14:16Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-wcs-app-761" successfully rolled out
  readyReplicas: 1
